# Generated by Django 5.0.3 on 2024-03-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('work_cutting', models.SmallIntegerField()),
                ('work_griding', models.SmallIntegerField()),
                ('work_filling', models.SmallIntegerField()),
                ('comments', models.TextField()),
                ('responsible', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('submitted_at', models.TimeField()),
                ('status', models.SmallIntegerField()),
            ],
        ),
    ]
